import yaml
from ruff_studio.ci_integration import generate_pre_commit_config, generate_github_actions_config

def test_generate_pre_commit_config():
    version = "0.1.0"
    content = generate_pre_commit_config(version)
    data = yaml.safe_load(content)

    assert 'repos' in data
    assert data['repos'][0]['repo'] == 'https://github.com/astral-sh/ruff-pre-commit'
    assert data['repos'][0]['rev'] == f'v{version}'

def test_generate_github_actions_config():
    version = "0.1.0"
    content = generate_github_actions_config(version)

    # Check for disclaimer
    assert content.startswith("# This workflow was generated by Ruff Studio.")

    # Strip disclaimer for yaml parsing
    yaml_content = content.split("\n", 1)[1]
    data = yaml.safe_load(yaml_content)

    assert data['name'] == 'Ruff'
    assert data['on'] == ['push', 'pull_request']
    assert 'ruff' in data['jobs']
    steps = data['jobs']['ruff']['steps']
    assert steps[0]['uses'] == 'actions/checkout@v4'
    assert steps[1]['uses'] == 'astral-sh/ruff-action@v1'
    assert steps[1]['with']['version'] == version
