"""
Handles the generation of CI/CD and pre-commit configurations.
"""
import yaml

def generate_pre_commit_config(ruff_version):
    """
    Generates the content for a .pre-commit-config.yaml file based on the
    current ruff version.
    """
    config = {
        'repos': [
            {
                'repo': 'https://github.com/astral-sh/ruff-pre-commit',
                'rev': f'v{ruff_version}',
                'hooks': [
                    {
                        'id': 'ruff',
                        'args': ['--fix']
                    },
                    {
                        'id': 'ruff-format'
                    }
                ]
            }
        ]
    }

    # Use yaml.dump to convert the Python dict to a YAML string
    # default_flow_style=False ensures lists and dicts are block-style
    return yaml.dump(config, default_flow_style=False, sort_keys=False)

def generate_github_actions_config(ruff_version):
    """
    Generates the content for a GitHub Actions workflow file that runs ruff.
    """
    config = {
        'name': 'Ruff',
        'on': ['push', 'pull_request'],
        'jobs': {
            'ruff': {
                'runs-on': 'ubuntu-latest',
                'steps': [
                    {
                        'uses': 'actions/checkout@v4'
                    },
                    {
                        'uses': 'astral-sh/ruff-action@v1',
                        'with': {
                            'version': ruff_version
                        }
                    }
                ]
            }
        }
    }

    # Add a disclaimer comment at the top
    disclaimer = "# This workflow was generated by Ruff Studio.\n"
    return disclaimer + yaml.dump(config, default_flow_style=False, sort_keys=False)
